baseURL = "/"
languageCode = "en-us"
title = "GIFMos"
googleAnalytics = "UA-97636604-1"
disqusShortname = "gifmos"
theme = "atchai"
relativeurls = true
canonifyurls = false
paginate = 10
pluralizelisttitles = false

[params]
  prod_baseurl = "https://gifmos.com"
  metadescription = "The world's first GIF social network"
  dateformat = "Jan 2, 2006" # Optional

[params.authors]
	[params.authors.DhirajGupta]
        name  = "Dhiraj Gupta - Tech lead"
        thumbnail		= "/img/authors/dhiraj.jpg"
        bio				= "Just an awesome guy"
        email   = "dhiraj@traversient.com"
        linkedin = "https://www.linkedin.com/in/dhiraj"
        twitter = "https://twitter.com/dhiraj"
        github = "https://github.com/dhiraj"
